i=1;
[X,C,SX] = RectifyAndDenseTriangulate(...
    CropBackground(...
    Cim{drp(i)},Unnormalize(CcorrsNormInFil{drp(i)}(1:2,:),K),1.1),...
    CropBackground(...
    Cim{drp(i)+1},Unnormalize(CcorrsNormInFil{drp(i)}(3:4,:),K),1.1),...
    K'\CEO{drp(i)}/K, K*CP{drp(i)}, K*CP{drp(i)+1},...
    {'plotCorrespondences','plotDisparityMap'});

psr({SX})